### ISSUE TITLE
oh yeah $help has spelling mistakes

### ISSUE THREAD

**Issue by tomerfir** [MissLummie/PinkieBot_discord#10]
you wrote PHASE like five times instead of PHRASE.
convert VAL's explanation is does not explain anything and is literally the same two words twice.
karma store should be in ' ' and should not have a dash inbetween the words.
also why tf are there no dots at the end of sentances is that because its a list or because i dunno

**Comment by alumag** [comment]
@shaharrose please take care of this issue

**Comment by alumag** [comment]
thank you for opening this issue. we will correct it in the next version.

**Comment by GitIsNotMyFriend** [comment]
1. You mentioned the wrong Shahar 😠 
2. Fixed and improved, will be implemented on the next update 👍
